[package]
name = "nomenclate-http"
version = "0.1.0"
authors = ["kilpatty <seanpkilgarriff@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.7"
serde = "1"
serde_derive = "1"
serde_json = "1"



